# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a debug APK"
  lane :build_debug do
    gradle(task: "assembleDebug")
  end

  desc "Build a release APK"
  lane :build_release do
    gradle(task: "assembleRelease")
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(task: "assembleRelease")
    upload_to_play_store
  end

  desc "Increment version code"
  lane :increment_version do
    increment_version_code(
      gradle_file_path: "../TutyFrutySlotForAndroid/build.gradle"
    )
  end

  desc "Take screenshots"
  lane :screenshots do
    capture_android_screenshots
  end

  # You can define as many lanes as you want
end
